# Generated by Django 5.1.15 on 2026-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reminder_type', models.CharField(blank=True, choices=[('absolute', 'Fecha específica'), ('relative', 'Minutos relativos')], max_length=10, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('external_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
